---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    require_chef_omnibus: latest
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
    require_chef_omnibus: latest
  run_list:
  - recipe[apt]

suites:
- name: aufs-package
  run_list:
  - recipe[aufs_test::default]
